# Generated by Django 3.2.7 on 2021-09-29 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=uuid.UUID('8912677d-a5f0-4788-84a4-11439a9598f8'), max_length=200),
        ),
    ]
