# Generated by Django 3.2.7 on 2021-09-29 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0002_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=uuid.UUID('7b0b457d-a6e4-463c-b09b-bc4e86145752'), max_length=200),
        ),
    ]
